# Generated by Django 5.1.1 on 2024-09-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('points', models.IntegerField()),
                ('is_member', models.BooleanField(default=True)),
                ('count_for_ranking', models.BooleanField(default=True)),
            ],
        ),
    ]
