# Generated by Django 5.1.1 on 2024-09-22 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_participant_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Nome Não Informado', max_length=30)),
                ('adress', models.CharField(default='Endereço não Informado', max_length=150)),
                ('city', models.CharField(default='Cidade não Informada', max_length=30)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('extra', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tornament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('name_tornament', models.CharField(default='Nome do Torneio não Informado.', max_length=30)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('position', models.PositiveIntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.participant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.round')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='tornament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.tornament'),
        ),
        migrations.CreateModel(
            name='NivelBlind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('small_blind', models.DecimalField(decimal_places=2, max_digits=10)),
                ('big_blind', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField()),
                ('tornament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.tornament')),
            ],
        ),
        migrations.CreateModel(
            name='FinalRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('position', models.PositiveIntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.participant')),
                ('tornament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.tornament')),
            ],
        ),
    ]
